# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Auroran Neon Alacritty                      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

[general]
import = []
live_config_reload = true

[env]
TERM = "alacritty"

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 12, y = 12 }
dynamic_padding = true
decorations = "Full"
opacity = 0.0
blur = true
startup_mode = "Windowed"
title = "Auroran Neon Terminal"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
size = 12.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.primary]
# Deep space background with neon contrast
background = "#FFFFFF"  # void_black from colors.conf
foreground = "#F0F6FC"  # soft_white from colors.conf
dim_foreground = "#7D8590"  # dim_grey from colors.conf

[colors.cursor]
text = "#0D1117"  # dark background for contrast
cursor = "#FFD700"  # auroran gold

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "#00D4FF"  # electric_blue from colors.conf

[colors.search]
matches = { foreground = "#0D1117", background = "#FFD700" }  # auroran_gold
focused_match = { foreground = "#0D1117", background = "#00FF88" }  # cyber_green

[colors.hints]
start = { foreground = "#0D1117", background = "#FF1493" }  # neon_pink
end = { foreground = "#0D1117", background = "#00CED1" }  # neon_teal

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#0D1117"
background = "#F0F6FC"

[colors.selection]
text = "CellBackground"
background = "#00D4FF"  # electric_blue

# Terminal colors inspired by the Auroran Neon palette
[colors.normal]
black = "#0D1117"    # void_black
red = "#FF4500"      # neon_red  
green = "#00FF88"    # cyber_green
yellow = "#FFD700"   # auroran_gold
blue = "#00D4FF"     # electric_blue
magenta = "#8A2BE2"  # neon_purple
cyan = "#00CED1"     # neon_teal
white = "#F0F6FC"    # soft_white

[colors.bright]
black = "#30363D"    # lighter surface_dark
red = "#FF6347"      # tomato red for better visibility
green = "#39FF14"    # brighter cyber_green
yellow = "#FFFF00"   # pure yellow for contrast
blue = "#1E90FF"     # dodger blue for visibility
magenta = "#DA70D6"  # orchid for better contrast
cyan = "#00FFFF"     # pure cyan for neon effect
white = "#FFFFFF"    # bright_white

[colors.dim]
black = "#1C2128"    # space_grey
red = "#B8341C"      # dimmer neon_red
green = "#00B85F"    # dimmer cyber_green
yellow = "#B8941C"   # dimmer auroran_gold
blue = "#0095B8"     # dimmer electric_blue
magenta = "#6B1F9F"  # dimmer neon_purple
cyan = "#009499"     # dimmer neon_teal
white = "#A8A8A8"    # dimmer white

[bell]
animation = "EaseOutExpo"
duration = 100
color = "#00D4FF"  # electric_blue flash

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.2

[terminal]
shell = { program = "/usr/bin/fish" }
osc52 = "CopyPaste"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
mouse = "Right"
action = "Paste"

[[mouse.bindings]]
mouse = "Middle"
action = "Paste"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\\\^⟨⟩`\\\\]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[hints.enabled.binding]
key = "O"
mods = "Control|Shift"

[keyboard]
bindings = [
    # Font size controls with neon theme
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    
    # Copy/Paste with neon aesthetics
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    
    # Search functionality
    { key = "F", mods = "Control|Shift", action = "SearchForward" },
    { key = "B", mods = "Control|Shift", action = "SearchBackward" },
    
    # Vi mode toggle
    { key = "Space", mods = "Control|Shift", action = "ToggleViMode" },
    
    # Window management
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "F11", action = "ToggleFullscreen" },
    
    # Scrolling
    { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
    { key = "Home", mods = "Shift", action = "ScrollToTop" },
    { key = "End", mods = "Shift", action = "ScrollToBottom" },
]

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
highlight_damage = false
prefer_egl = true
