theme_name = "Auroran Neon"
theme_description = "A visually captivating theme inspired by the Sweet theme and Beautyline icon designs all mixed with an auroran flair"
theme_version = "0.1"
theme_author = "Kit Kabbit"
theme_license = "GPL-3.0"
